### ISSUE TITLE
Repo/Gist Date Parser Action Example

### ISSUE THREAD

**Issue by kzndotsh** [kzndotsh/awesome-discordpy#3]
### Step 1: Create the GitHub Action Workflow

Create a file under `.github/workflows/update-repo-dates.yml` with the following content:

```yaml
name: Update Repo Creation Dates

on:
  push:
    branches:
      - main  # or your main branch
  pull_request:
    branches:
      - main  # or your main branch
  workflow_dispatch:

jobs:
  update_repo_dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the required Python version

      - name: Install requirements
        run: |
          python -m pip install requests pyyaml

      - name: Run update script
        run: python .github/scripts/update_repo_dates.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add YOUR_MARKDOWN_FILE.md
          git commit -m 'Update repo creation dates'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Step 2: Create the Update Script

Create a script at `.github/scripts/update_repo_dates.py` to handle the logic for fetching repo creation dates and updating the markdown file:

```python
import re
import requests
import os

# Your markdown file
markdown_file = 'YOUR_MARKDOWN_FILE.md'

# Regex to find GitHub repo links (e.g., https://github.com/user/repo)
repo_link_pattern = re.compile(r"https://github\.com/[^/\s]+/[^/\s]+")

# Function to get repo creation date
def get_repo_creation_date(repo_url):
    api_url = repo_url.replace("https://github.com", "https://api.github.com/repos")
    headers = {'Authorization': f'token {os.getenv("GITHUB_TOKEN")}'}
    response = requests.get(api_url, headers=headers)
    if response.status_code == 200:
        data = response.json()
        return data.get('created_at', 'N/A')
    return 'N/A'

# Read the markdown file
with open(markdown_file, 'r') as file:
    content = file.read()

# Find all repo links
repo_links = repo_link_pattern.findall(content)

# Updating the markdown content
for repo_link in repo_links:
    creation_date = get_repo_creation_date(repo_link)
    if creation_date == 'N/A':
        continue
    # Append creation date to repo link (or adjust as necessary)
    updated_link = f"{repo_link} (created on {creation_date})"
    content = content.replace(repo_link, updated_link)

# Write back the updated content to the markdown file
with open(markdown_file, 'w') as file:
    file.write(content)
```
